-- Create contact_messages table
create table contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  read boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS policies
alter table contact_messages enable row level security;

create policy "Public insert contact_messages"
  on contact_messages for insert
  with check (true);

create policy "Admin manage contact_messages"
  on contact_messages for all
  using (auth.role() = 'authenticated'); 