-- Create projects table
create table projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image_url text not null,
  category text not null check (category in ('mining', 'construction', 'logistics', 'engineering')),
  status text not null check (status in ('completed', 'ongoing', 'upcoming')),
  client text not null,
  location text not null,
  start_date date not null,
  end_date date,
  order integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS policies
alter table projects enable row level security;

create policy "Public read projects"
  on projects for select
  using (true);

create policy "Admin manage projects"
  on projects for all
  using (auth.role() = 'authenticated');

-- Create trigger for updated_at
create trigger update_projects_updated_at
  before update on projects
  for each row
  execute function update_updated_at_column(); 