-- Create partners table
create table partners (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  logo_url text not null,
  website_url text,
  category text not null check (category in ('client', 'supplier', 'collaborator')),
  order integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS policies
alter table partners enable row level security;

create policy "Public read partners"
  on partners for select
  using (true);

create policy "Admin manage partners"
  on partners for all
  using (auth.role() = 'authenticated');

-- Create trigger for updated_at
create trigger update_partners_updated_at
  before update on partners
  for each row
  execute function update_updated_at_column(); 