-- Create activity_logs table
create table activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  action text not null,
  entity_type text not null check (entity_type in ('service', 'message', 'user', 'project', 'partner', 'quote')),
  entity_id text not null,
  details text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS policies
alter table activity_logs enable row level security;

create policy "Admin view activity logs"
  on activity_logs for select
  using (auth.role() = 'authenticated');

create policy "Admin insert activity logs"
  on activity_logs for insert
  with check (auth.role() = 'authenticated'); 